version: '2'
services:
  gitreceive:
    build:
      context: .
    ports:
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - PAUS_BASE_DOMAIN=pausapp.com
      - PAUS_DOCKER_HOST=tcp://172.17.8.101:2375
      - PAUS_ETCD_ENDPOINT=http://172.17.8.101:2379
      - PAUS_MAX_APP_DEPLOY=2
      - PAUS_REPOSITORY_DIR=/repos
      - PAUS_URI_SCHEME=http
  gitreceive-upload-key:
    extends: gitreceive
    volumes_from:
      - gitreceive
    entrypoint: /usr/local/bin/upload-key
