#!/bin/bash

set -e

#
# Source from:
#   https://github.com/progrium/gitreceive/wiki/TipsAndTricks#handling-submodules
#

git config -f .gitmodules --get-regexp '^submodule\..*\.path$' |
  while read path_key path
  do
    rm -fr $path
    url_key=`echo $path_key | sed 's/\.path/.url/'`
    url=`git config -f .gitmodules --get "$url_key"`
    git submodule add $url $path
  done
