#!/bin/bash

set -e

BASE_DIR=`pwd`
# https://github.com/docker/docker/issues/8395#issuecomment-57918396
HOST_IP=`ip route show 0.0.0.0/0 | grep -Eo 'via \S+' | awk '{ print $2 }'`

exit_code=0

echo "Repository: $1"
echo "Revision: $2"
echo "Username: $3"
echo "Fingerprint: $4"

mkdir -p /tmp/build/$1 || true
cat | tar -x -C /tmp/build/$1
cd /tmp/build/$1

if [[ -f docker-compose.yml ]]; then
  echo "docker-compose.yml was detected"
  DOCKER_HOST=tcp://$HOST_IP:2375 docker-compose -p $1$2 build
  DOCKER_HOST=tcp://$HOST_IP:2375 docker-compose -p $1$2 pull
  DOCKER_HOST=tcp://$HOST_IP:2375 docker-compose -p $1$2 up -d
else
  echo "docker-compose.yml was NOT found!"
  exit_code=1
fi

cd $BASE_DIR
rm -rf /tmp/build/$1

exit $exit_code
